name: Continuous Release (DEV)

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Name of the release version"
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "New version that will be used for development"
        required: true
        default: "X.Y.Z-SNAPSHOT"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 21
          maven-version: 3.9.6

      - name: Configure Git user
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"

      - name: Clean release
        run: mvn --batch-mode release:clean
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare release
        run: mvn --batch-mode --update-snapshots release:prepare -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform release
        run: mvn --batch-mode release:perform -Darguments="-Dmaven.deploy.skip=true"
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload To GHCR
        run: mvn --batch-mode --update-snapshots clean package -P cd
        env:
          GITHUB_ACTOR: ${{ secrets.PERSONAL_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Create archive
        id: create_archive
        run: >-
          git archive -o "release-v${{ github.event.inputs.releaseVersion }}.zip" ${{ github.ref_name }}

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }}
          "release-v${{ github.event.inputs.releaseVersion }}.zip"
          --generate-notes
          --title "Version ${{ github.event.inputs.releaseVersion }}"